## Distance Matrix Computation

In [1]:
import numpy as np

In [2]:
def eucleiden_distance(a: np.ndarray,b: np.ndarray)->  np.ndarray:
    diff = a - b
    ssd = np.sum(diff**2, axis=1)
    return np.sqrt(ssd)

def distance_matrix(x: np.ndarray) -> np.ndarray:
    no_of_obs,no_of_feature = x.shape
    i, j = np.triu_indices(no_of_obs, k=1) # Upeer Traingular index Without Diagonal index
    a = x[i]                    # Selecting elements for upper triangular distance computation
    b = x[j]                    # Selecting elements for upper triangular distance computation 
    upper_triangle_distance =  eucleiden_distance(a,b)
    d_mat = np.zeros((no_of_obs, no_of_obs))    # Distance Matrix with all 0
    d_mat[i,j] = upper_triangle_distance # Filling Up Upper Triangular Matrix
    d_mat = d_mat + d_mat.T     # Filling Up lower Triangular Matrix
    return d_mat 


Let $X^{i}$ is Vector such that $\forall X^{i}\in \mathbb{R}^{n}$

And $D(X^{i},X^{j})$ is the distance between $X^{i},X^{j}$


$\large \begin{bmatrix}
X^{1}\\
X^{2}\\
X^{3}\\
\vdots\\
X^{m}\\
\end{bmatrix}
\text{Pairwise Distance} \Rightarrow   \begin{bmatrix} 
D(X^{1},X^{1}) & D(X^{1},X^{2}) & D(X^{1},X^{3}) & \dots  & D(X^{1},X^{m}) \\
D(X^{2},X^{1}) & D(X^{2},X^{2}) & D(X^{2},X^{3}) & \dots  & D(X^{2},X^{m}) \\
D(X^{3},X^{1}) & D(X^{3},X^{2}) & D(X^{3},X^{3}) & \dots  & D(X^{3},X^{m}) \\
\vdots \\
D(X^{m},X^{1}) & D(X^{m},X^{2}) & D(X^{m},X^{3}) & \dots  & D(X^{m},X^{m}) \\
\end{bmatrix}
$


Total number of distance calculation is $\large  m^{2}$

if $\large  D(X^{i},X^{j})$ is commutative or  $\large  D(X^{i},X^{j}) = D(X^{j},X^{i})$, then Distance Matrix will be symmetric

So we need to calculate only upper triangle matrix element , which is $\large  \frac{m^{2}}{2}$ computation

and if $\large  D(X^{i},X^{i}) = 0 $ then diagonal elements will be always 0 so we have todo $\large  \frac{m^{2}}{2} - m$ computation

total computation  = $\large \frac{m(m-1)}{2}$



### Data has 3 observation m=3 and n =2

In [3]:
x = np.array([[0,0],[3,4],[3,5]])
print(x)

[[0 0]
 [3 4]
 [3 5]]


### Upper Traingular matrix indicies

In [4]:
m,n = x.shape
#i, j = np.triu_indices(m,)      #With Diagonal elements 
i, j = np.triu_indices(m, k=1)  #Without Diagonal elements  
print(i,j)

[0 0 1] [1 2 2]


$\begin{bmatrix} 
D(0,0) & D(0,1) & D(0,2)\\
D(1,0) & D(1,1) & D(1,2)\\
D(2,0) & D(2,1) & D(2,2)\\
\end{bmatrix} \Rightarrow
\begin{bmatrix}
. & D(0,1) & D(0,2)\\
. & . & D(1,2)\\
. & . & .\\
\end{bmatrix}
$

### Upper traingle elements for distance computations

In [5]:
a = x[i]  #  x[i]  
b = x[j]

print(a)
print(b)

[[0 0]
 [0 0]
 [3 4]]
[[3 4]
 [3 5]
 [3 5]]


### Euclide Distance computation using for upper traingular elements

In [6]:
def eucleiden_distance(a,b):
    diff = a-b
    ssd = np.sum(diff**2, axis=1)
    return np.sqrt(ssd)

upper_distance =  eucleiden_distance(a,b)
print(upper_distance)

[5.         5.83095189 1.        ]


### creating distance matrix with all 0

In [7]:
d_mat = np.zeros((m, m))
d_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Filling upper traingular matrix

In [8]:
d_mat[i,j] = upper_distance
d_mat

array([[0.        , 5.        , 5.83095189],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        ]])

### Filling up lowe trangular matrix

In [9]:
d_mat = d_mat + d_mat.T
d_mat

array([[0.        , 5.        , 5.83095189],
       [5.        , 0.        , 1.        ],
       [5.83095189, 1.        , 0.        ]])